### PR TITLE
Fix bug that was causing the computational commitment verification to fail

### LINKED ISSUE #6: debug the computational commitment evaluation function
Currently the `verify` function in the computational commitment returns false https://github.com/maramihali/Spartan/blob/master/src/lib.rs#L473 because of a sumcheck evaluation. As this was not an issue at least up to verison https://github.com/maramihali/Spartan/tree/632b95b4c83def568e35db5e022f0e3f0e333e31 , investigate where the bug was introduced.

### PR DESCRIPTION
**Pull request by maramihali**
Fixes #6 

On the verifier's side, the transcript is updated partially inside the circuit and this causes the Spartan-SNARK verification to fail when the computational commitment is checked because the verifier's transcript outside the circuit was inconsistent wrt the prover's transcript. This PR provides a way to address the problem.

### CODE REVIEW

File: src/constraints.rs [hunk 1]
```diff
@@ -386,13 +388,20 @@ impl ConstraintSynthesizer<Fr> for R1CSVerificationCircuit {
...
+    let eval_C_r_var = FpVar::<Fr>::new_witness(cs.clone(), || Ok(eval_C_r))?;
 
     let scalar_var = &r_A_var * &eval_A_r_var + &r_B_var * &eval_B_r_var + &r_C_var * &eval_C_r_var;
 
     let expected_claim_post_phase2_var = eval_Z_at_ry_var * scalar_var;
     claim_post_phase2_var.enforce_equal(&expected_claim_post_phase2_var)?;
 
+    let expected_transcript_state_var = transcript_var.challenge()?;
+    let claimed_transcript_state_var =
+      FpVar::<Fr>::new_witness(cs, || Ok(self.claimed_transcript_sat_state))?;
```
Comment (nikkolasg) [inline src/constraints.rs:400]: This all looks correct to - one question though: shouldn't this be a public input ? I think the verifier needs to pass this as public input to the groth16 verification to make sure the state from the prover is the same one generated "Inside the circuit". If it's a witness, then the prover can input anything, the verifier can't check it's the same value.

Or am i missing something ?

Comment (maramihali) [reply src/constraints.rs:400]: No, you're right. Thanks for spotting this
